var itensIniciais = [
  { nome: "Abacate", img: "img/abacate.webp" },
  { nome: "Abacaxi", img: "img/abacaxi.webp" },
  { nome: "Ameixa", img: "img/ameixa.webp" },
  { nome: "Banana-maçã", img: "img/bananamaca.webp" },
  { nome: "Banana-nanica", img: "img/bananananinca.webp" },
  { nome: "Banana-prata", img: "img/bananaprata.webp" },
  { nome: "Caqui Chocolate", img: "img/caquichocolate.webp" },
  { nome: "Caqui Fuyu", img: "img/caquifuyu.webp" },
  { nome: "Caqui Rama Forte", img: "img/caquiramaforte.webp" },
  { nome: "Carambola", img: "img/carambola.webp" },
  { nome: "Cereja", img: "img/cereja.webp" },
  { nome: "Figo Roxo", img: "img/figoroxo.webp" },
  { nome: "Fruta-do-conde", img: "img/frutadoconde.webp" },
  { nome: "Goiaba Branca", img: "img/goiababranca.webp" },
  { nome: "Goiaba Vermelha", img: "img/goiabavermelha.webp" },
  { nome: "Kiwi", img: "img/kiwi.webp" },
  { nome: "Laranja Lima", img: "img/laranjalima.webp" },
  { nome: "Laranja Pera", img: "img/laranjapera.webp" },
  { nome: "Limão Cravo", img: "img/limaocravo.webp" },
  { nome: "Limão Siciliano", img: "img/limaosiciliano.webp" },
  { nome: "Limão Taiti", img: "img/limaotaiti.jpeg" },
  { nome: "Maçã Fuji", img: "img/macafuji.webp" },
  { nome: "Maçã Gala", img: "img/macagala.webp" },
  { nome: "Mamão Formosa", img: "img/mamaoformosa.webp" },
  { nome: "Mamão Papaya", img: "img/mamaopapaya.webp" },
  { nome: "Manga Palmer", img: "img/mangapalmer.webp" },
  { nome: "Maracujá Azedo", img: "img/maracujaazedo.webp" },
  { nome: "Maracujá Doce", img: "img/maracujadoce.webp" },
  { nome: "Melancia", img: "img/melancia.webp" },
  { nome: "Melão Amarelo", img: "img/melaoamarelo.webp" },
  { nome: "Melão Cantaloupe", img: "img/melaocantaloupe.webp" },
  { nome: "Mexerica", img: "img/mexirica.webp" },
  { nome: "Morango", img: "img/morangos.webp" },
  { nome: "Nectarina", img: "img/nectarina.webp" },
  { nome: "Pera Portuguesa", img: "img/peraportuguesa.webp" },
  { nome: "Pera Williams", img: "img/perawillians.webp" },
  { nome: "Pêssego", img: "img/pessego.webp" },
  { nome: "Tangerina", img: "img/tangerina.webp" },
  { nome: "Uva Itália", img: "img/uvaitalia.webp" },
  { nome: "Uva Niágara", img: "img/uvaniagra.webp" },
  { nome: "Uva Rubi", img: "img/uvarubi.webp" },
  { nome: "Uva Thompson", img: "img/uvathompson.webp" },
  { nome: "Uva Vitória", img: "img/uvavitoria.webp" }
];